let photoList = [
    {
      img: "Photos/cryptopunks/cp15.png",
      id: 0,
    
    },
    {
      img: "Photos/cryptopunks/cp12.png",
      id: 1,
      
    },
    {
        img:"Photos/cryptopunks/cp01.png",
        id:2,
    },
    {
        img:"Photos/cryptopunks/cp27.png",
        id:3,

    },
    {

        img:"Photos/cryptopunks/cp32.png",
        id:4,

    },
    {
        img:"Photos/cryptopunks/cp03.png",
        id:5,
    },
    {
        img:"Photos/cryptopunks/cp11.png",
        id:6,
    },
    {
        img:"Photos/cryptopunks/cp16.png",
        id:7,
    },
    {
        img:"Photos/cryptopunks/cp17.png",
        id:8,
    },
    {
        img:"Photos/cryptopunks/cp13.png",
        id:9,
    },
    {
        img:"Photos/cryptopunks/cp25.png",
        id:10,
    },
    {
        img:"Photos/cryptopunks/cp19.png",
        id:11,
    },
    {
        img:"Photos/cryptopunks/cp23.png",
        id:12,
    },
    {
        img:"Photos/cryptopunks/cp14.png",
        id:13,
    },
    {
        img:"Photos/cryptopunks/cp20.png",
        id:14,
    },
    {
        img:"Photos/cryptopunks/cp08.png",
        id:15,
    },
    {
        img:"Photos/cryptopunks/cp02.png",
        id:16,
    },
    {
        img:"Photos/cryptopunks/cp30.png",
        id:17,
    },
    {
        img:"Photos/cryptopunks/cp04.png",
        id:18,
    },
    {
        img:"Photos/cryptopunks/cp29.png",
        id:19,
    },
    {
        img:"Photos/cryptopunks/cp09.png",
        id:20,
    },
    {
        img:"Photos/cryptopunks/cp21.png",
        id:21,
    },
    {
        img:"Photos/cryptopunks/cp07.png",
        id:22,
    },
      {
        img:"Photos/cryptopunks/cp18.png",
        id:23,
    },{
        img:"Photos/cryptopunks/cp28.png",
        id:24,
    },
    {
        img:"Photos/cryptopunks/cp10.png",
        id:25,
    },
    {
        img:"Photos/cryptopunks/cp24.png",
        id:26,
    },
    {
        img:"Photos/cryptopunks/cp06.png",
        id:27,
    },
    {
        img:"Photos/cryptopunks/cp06.png",
        id:27,
    },
    {
        img:"Photos/cryptopunks/cp34.png",
        id:28,
    },
    {
        img:"Photos/cryptopunks/cp33.png",
        id:29,
    },
    {
        img:"Photos/cryptopunks/cp35.png",
        id:31,
    },
    {
        img:"Photos/cryptopunks/cp38.png",
        id:32,
    },
    {
        img:"Photos/cryptopunks/cp39.png",
        id:33,
    },
    {
        img:"Photos/cryptopunks/cp40.png",
        id:34,
    },
    {
        img:"Photos/cryptopunks/cp36.png",
        id:35
    },
    {
        img:"Photos/cryptopunks/cp41no.png",
        id:36
    },
  ];
  
  